changes
MCreator/Generator-Forge-1.14.4 pull request #3
Opened 2021-04-23 00:03 UTC by Fisheiyy

minor changes to follow in the path of changes that directly impact mcreator

2021-04-23 00:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MCreator/Generator-Forge-1.14.4?pullRequest=3) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MCreator/Generator-Forge-1.14.4?pullRequest=3) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MCreator/Generator-Forge-1.14.4?pullRequest=3) it.</sub>

2021-04-23 07:34 UTC, KlemenDEV requested changes

2021-04-23 07:34 UTC, KlemenDEV commented on forge-1.14.4/workspacebase/build.gradle
> +    mappings channel: 'snapshot', version: '20200119-1.14.4'
Mappings should not be changed like this as names and mappings system in the generator may break. Keep existing mappings.

2021-04-23 22:09 UTC, Fisheiyy commented on forge-1.14.4/workspacebase/build.gradle
> +    mappings channel: 'snapshot', version: '20200119-1.14.4'
it honestly might be best though to go through and update to newer mappings since this is written technically as a 1.14.3 generator or atleast the mappings are, will look into this though but for now i will revert

2021-04-24 07:22 UTC, KlemenDEV commented on forge-1.14.4/workspacebase/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.8.1-all.zip
If you update the wrapper version, update the wrapper JAR too.

2021-04-24 18:40 UTC, KlemenDEV requested changes
Checking again this version of forge gradle does not work with the gradle wrapper you provided, please revert gradle wrapper update.

2021-04-24 21:37 UTC, Fisheiyy commented
i could update forge gradle along with gradle but im not sure any newer version of forge gradle is compatible with this version of minecraft

2021-04-25 07:25 UTC, KlemenDEV approved these changes

2021-04-25 07:25 UTC, merged

2021-04-26 04:55 UTC, Fisheiyy commented
oh uhh hey make sure to make a 2021.1 branch and delete 2020.6

2021-04-26 06:01 UTC, KlemenDEV commented
There is no need for subversion here, also not in 1.12.2 but it slipped in with my PR.